stages:
 - pre-build
 - test
 - docs
 - build
 - deploy

requirements:
 type: pre-build
 tags:
 - python2
 - linux
 - raspberrypi
 script:
 - python2 -m pip install -r requirements.txt --user

epydoc:
 type: docs
 only:
 - master
 artifacts:
  paths:
  - html/
 tags:
 - python2
 - linux
 - raspberrypi
 script:
 - wget https://git.gwillz.com.au/snippets/9/raw -O doc-style.css -q
 - python2 -m pip install pylint epydoc docutils --user -q
 - >-
   epydoc --no-sourcecode --no-frames --output html --simple-term -vv
   --inheritance grouped --css doc-style.css --name 'ShiftPi' shiftpi

pypi:
 type: build
 only:
 - master
 artifacts:
  paths:
  - dist/
 tags:
 - python2
 - linux
 - raspberrypi
 script:
 - python2 setup.py bdist_wheel

deploy:
 type: deploy
 only:
 - master
 dependencies:
 - epydoc
 - pypi
 tags:
 - linux
 - mk2-docs
 script:
 - '[ -e /srv/api/shiftpi ] || mkdir /srv/api/shiftpi'
 - '[ -e /srv/pypi/packages/shiftpi ] || mkdir /srv/pypi/packages/shiftpi'
 - cp html/* -r /srv/api/shiftpi
 - cp dist/*.whl /srv/pypi/packages/shiftpi

lint:
 type: test
 tags:
 - python2
 - linux
 - raspberrypi
 script:
 - wget https://git.gwillz.com.au/snippets/8/raw -O mk2pylint.cfg -q
 - pylint --rcfile=mk2pylint.cfg shiftpi --reports=no --disable=fixme || [[ $(($? & 3)) == 0 ]]
