stages:
 - docs
 - test
 - build
 - deploy

epydoc:
 stage: docs
 only:
 - master
 - tag
 artifacts:
  paths:
  - html/
 tags:
 - python3
 - linux
 - raspberrypi
 script:
 - wget https://git.gwillz.com.au/snippets/9/raw -O doc-style.css -q
 - >-
   epydoc --no-sourcecode --no-frames --output html --simple-term -vv
   --inheritance grouped --css doc-style.css --name 'ShiftPi' shiftpi

pypi:
 stage: build
 only:
 - master
 - tag
 artifacts:
  paths:
  - dist/
 tags:
 - python3
 - linux
 - raspberrypi
 script:
 - python3 setup.py bdist_wheel --universal

deploy:
 stage: deploy
 only:
 - master
 - tag
 dependencies:
 - epydoc
 - pypi
 tags:
 - linux
 - mk2-docs
 script:
 - '[ -e /srv/api/shiftpi ] || mkdir /srv/api/shiftpi'
 - '[ -e /srv/pypi/packages/shiftpi ] || mkdir /srv/pypi/packages/shiftpi'
 - cp html/* -r /srv/api/shiftpi
 - cp dist/*.whl /srv/pypi/packages/shiftpi

lint:
 stage: test
 tags:
 - python3
 - linux
 - raspberrypi
 script:
 - wget https://git.gwillz.com.au/snippets/8/raw -O mk2pylint.cfg -q
 - 'python3 -m pylint --rcfile=mk2pylint.cfg shiftpi --reports=no || [[ $(($? & 3)) == 0 ]]'
